### ISSUE TITLE
api-container exited with code 1

### ISSUE THREAD

**Issue by ahmedgenina** [MatheusINFO/ReserCAR#1]
Rodar o "docker-compose up" em uma nova instalação de "linux ubuntu 20" retorna o erro abaixo :

api-container exited with code 1
api-container |
api-container | > resercar@3.0.0 start /usr/src/api
api-container | > node dist/main/server.js
api-container |
api-container | internal/modules/cjs/loader.js:883
api-container |   throw err;
api-container |   ^
api-container |
api-container | Error: Cannot find module '/usr/src/api/dist/main/server.js'
api-container |     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
api-container |     at Function.Module._load (internal/modules/cjs/loader.js:725:27)
api-container |     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
api-container |     at internal/main/run_main_module.js:17:47 {
api-container |   code: 'MODULE_NOT_FOUND',
api-container |   requireStack: []
api-container | }
api-container | npm ERR! code ELIFECYCLE
api-container | npm ERR! errno 1
api-container | npm ERR! resercar@3.0.0 start: `node dist/main/server.js`
api-container | npm ERR! Exit status 1
api-container | npm ERR!
api-container | npm ERR! Failed at the resercar@3.0.0 start script.
api-container | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
api-container |
api-container | npm ERR! A complete log of this run can be found in:
api-container | npm ERR!     /root/.npm/_logs/2021-04-25T02_34_06_232Z-debug.log
api-container exited with code 1

**Comment by MatheusINFO** [comment]
Corrigido, a pasta dist não estava sendo criada nem no repositório, por isso não era encontrada.

![image](https://user-images.githubusercontent.com/48860569/116001286-189f4500-a5ca-11eb-94d2-096f60a958e2.png)
