### ISSUE TITLE
Erro no cadastro do  veiculo 

### ISSUE THREAD

**Issue by ahmedgenina** [MatheusINFO/ReserCAR#2]
OS 3 containers estão rodando, porem o cadastro de um veiculo retorno o erro em anexo 
![error_cadastro](https://user-images.githubusercontent.com/8081993/116009608-fd93fb80-a5f0-11eb-84ca-c90c4712e8ab.png)
![docker_containers](https://user-images.githubusercontent.com/8081993/116009611-0553a000-a5f1-11eb-845f-4167643a253e.png)

**Comment by MatheusINFO** [comment]
Subi um vídeo no imgur utilizando o sistema: https://imgur.com/a/iIZSfHd
Não consegui simular o erro mostrado aqui na máquina.
Quais parâmetros foram utilizados?
